version: "1"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: dating-postgres
    networks:
      - resource-network
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dating
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres - dating"]
      interval: 1s
      timeout: 50s
      retries: 50
    command: ["postgres", "-c", "log_statement=all"]

networks:
  resource-network:
    driver: bridge
